### ISSUE TITLE
will the dataset be open？your data link is empty

### ISSUE THREAD

**Issue by whx57** [taohan10200/WEATHER-5K#1]

**Comment by taohan10200** [comment]
WEATHER-5K is released, please feel free to download.

**Comment by whx57** [comment]
thanks so much, your work means a lot to me



---Original---
From: "tao ***@***.***&gt;
Date: Fri, Jun 14, 2024 16:49 PM
To: ***@***.***&gt;;
Cc: "Hu ***@***.******@***.***&gt;;
Subject: Re: [taohan10200/WEATHER-5K] will the dataset be open？your data link is empty (Issue #1)




 
WEATHER-5K is released, please feel free to download.
